# Orderer Definition
# Note: if using raft consensus, define n+1 orderers.
#       if using solo consensus, just define 1 orderer (orderer.example.com)
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
        SANS:
          - orderer.example.com
          - localhost
      - Hostname: orderer1.org1Name
        SANS:
          - orderer1.org1Name.example.com
          - localhost
      - Hostname: orderer2.org2Name
        SANS:
          - orderer2.org2Name.example.com
          - localhost

# Peer Definition
# Note: Peer name orderer starts from 0. peer0, peer1, etc.
PeerOrgs:
  - Name: org1Name
    Domain: org1Name.example.com
    EnableNodeOUs: true
    Template:
      Count: 1 # How many peer will be generated
    Users:
      Count: 1 # The number of user accounts _in addition_ to Admin
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.org1Name.example.com
          - localhost

  - Name: org2Name
    Domain: org2Name.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.org2Name.example.com
          - localhost
